# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  $ip = "69.140.140.141"
  $vmname = "emacs28-archlinux"

  config.vbguest.auto_update = false
  config.vbguest.no_remote = true
  config.vm.box = "terrywang/archlinux"
  config.vm.box_version = "3.21.0707"

  config.vm.define $vmname do |node|
    node.vm.network "private_network", ip: $ip
    node.vm.hostname = $vmname
    node.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      # VMSVGA seems to perform okay, so this will be outcommented for now
      # vb.customize ['modifyvm', :id, '--graphicscontroller', 'vboxsvga']
      vb.customize ["modifyvm", :id, "--vram", "128"]
      vb.name = $vmname
      vb.memory = 2048
      vb.cpus = 2
    end
  end
  config.vm.provision "Place VM dotfiles", type: "file" do |f|
    f.source = "../dotfiles_vm/."
    f.destination = "/home/vagrant"
  end
  config.vm.provision "Re-install guest additions (X), X and tools", type: "shell" do |s|
    s.privileged = true
    s.inline = <<-SHELL
     pacman -R virtualbox-guest-utils-nox --noconfirm
     pacman -Sy virtualbox-guest-utils emacs vim xorg-server xorg-xinit xterm git cmake fd llvm ripgrep aspell aspell-en languagetool --noconfirm --needed
     SHELL
    #s.reboot = true
  end
  # This will pull "my" dotfiles, if you are not me, then you might not want this behaviour
  config.vm.provision "Use chezmoi to fetch dotfiles from gitrepo", type: "shell" do |s|
    s.privileged = true
    s.inline = <<-SHELL
     pacman -Sy chezmoi --noconfirm --needed
     sudo -iu vagrant /bin/bash -c 'chezmoi init --apply schwanberger'
     SHELL
  end
  config.vm.provision "Clone Doom Emacs repo", type: "shell" do |s|
    s.privileged = false
    s.inline = <<-SHELL
     git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
     SHELL
  end
end
