# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  ip = '69.140.140.141'
  vmname = 'emacs28-archlinux'

  config.vbguest.auto_update = false
  config.vbguest.no_remote = true
  config.vm.box = 'terrywang/archlinux'
  config.vm.box_version = '3.21.1208'
  config.vm.synced_folder 'C:\\', '/c/', id: 'windows-root',
                                         owner: 'root',
                                         group: 'root',
                                         mount_options: ['dmode=777,fmode=777']
  config.vm.define vmname do |node|
    node.vm.network 'private_network', ip: ip
    # node.vm.network 'forwarded_port', guest: 22, host: 2666
    node.vm.hostname = vmname
    node.vm.provider 'virtualbox' do |vb|
      vb.gui = false
      vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
      # VMSVGA seems to perform okay, so this will be outcommented for now
      # vb.customize ['modifyvm', :id, '--graphicscontroller', 'vboxsvga']
      vb.customize ['modifyvm', :id, '--vram', '128']
      vb.name = vmname
      vb.memory = 4096
      vb.cpus = 6
    end
  end
  # config.vm.provision 'Place VM dotfiles', type: 'file' do |f|
  #   f.source = '../dotfiles_vm/.'
  #   f.destination = '/home/vagrant'
  # end
  config.vm.provision 'Emacs 27/28 pre-reqs', type: 'shell' do |s|
    s.privileged = false
    s.path = '../scripts/packages_prereq.sh'
    # s.reboot = true
  end
  config.vm.provision 'Pacman update', type: 'shell' do |s|
    s.privileged = true
    s.inline = <<-SHELL
    pacman -Syyu --noconfirm
    SHELL
    # s.reboot = true
  end
  config.vm.provision 'Emacs 28 compilation (native-comp)', type: 'shell' do |s|
    s.privileged = false
    s.path = '../scripts/emacs28_install.sh'
    # s.reboot = true
  end
  # This will pull "my" dotfiles, if you are not me, then you might not want this behaviour
  config.vm.provision 'Use chezmoi to fetch dotfiles from gitrepo', type: 'shell' do |s|
    s.privileged = true
    s.inline = <<-SHELL
     pacman -Sy chezmoi --noconfirm --needed
     sudo -iu vagrant /bin/bash -c 'chezmoi init --apply --verbose https://github.com/schwanberger/dotfiles.git'
    SHELL
  end
  config.vm.provision 'Clone Doom Emacs repo', type: 'shell' do |s|
    s.privileged = false
    s.inline = <<-SHELL
     git clone --depth 1 https://github.com/hlissner/doom-emacs ~/doom-vertico
    SHELL
  end
  config.vm.provision 'Allow X11 forwarding', type: 'shell' do |s|
    s.privileged = true
    s.inline = <<-SHELL
     sed -i 's/^#X11Forwarding no/X11Forwarding yes/' /etc/ssh/sshd_config
     systemctl restart sshd
    SHELL
  end
  config.vm.provision 'Set timezone to Europe/Copenhagen', type: 'shell' do |s|
    s.privileged = true
    s.inline = <<-SHELL
      timedatectl set-timezone "Europe/Copenhagen"
    SHELL
  end
  config.vm.provision 'Start doom install (+native compile)', type: 'shell' do |s|
    s.privileged = false
    s.inline = <<-SHELL
      export DOOMDIR=~/doom-vertico-config
      ~/doom-vertico/bin/doom -y install
    SHELL
  end
end
